- hosts: all
  become: false
  tasks:
    - name: create new deployment
      command: kubectl apply -f /home/rockylinux/Deployment.yml
    - name: create new service 
      command: kubectl apply -f /home/rockylinux/Service.yml
            
