FROM centos:latest


# MAINTAINER YourName/YourOrganization


# Use dnf for package management
RUN dnf install -y httpd zip unzip


# Download the zip file using curl
curl -L https://ww.free.css.com/assets/files/free-css-templates/download/page254/photogenic.zip -o /var/www/html/photogenic.zip


# Unzip and copy files in one step
RUN unzip /var/www/html/photogenic.zip && cp -rf photogenic/* /var/www/html/


# Remove intermediate files
RUN rm -rf photogenic photogenic.zip


# Set the entrypoint command
ENTRYPOINT ["/usr/sbin/httpd", "0", "FOREGROUND"]


EXPOSE 80  # Corrected port to 80 for standard http access


WORKDIR /var/www/html/
