apiVersion: v1 # Kubernetes API version for services
kind: Service # Kind of object being defined (Service in this case)
metadata:
  name: sagar # Name of the service
  labels:
    app: sagar
spec:
  selector: # Labels to identify pods for this service
    app: sagar # Match pods with the same label
  type: LoadBalancer # Type of service (e.g., ClusterIP, LoadBalancer)
  ports: # Ports exposed by the service
  - port: 8080 # Port number exposed by the service
    targetPort: 80 # Port number the service forwards to in the pod containers
   # nodeport: 31200
